server:
  port: 55000

spring:
  application:
    name: service-business-mall
# rabbitmq 配置
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

ribbon:
  # 设置连接超时时间
  ConnectTimeout: 600
  # 设置读取超时时间
  ReadTimeout: 6000
  # 对所有操作请求都进行重试
  OkToRetryOnAllOperations: true
  # 切换实例的重试次数
  MaxAutoRetriesNextServer: 2
  # 对当前实例的重试次数
  MaxAutoRetries: 1

feign:
  compression:
    request:
      # 配置请求GZIP压缩
      enabled: true
      # 配置压缩数据大小的下限
      min-request-size: 2048
      # 配置压缩支持的MIME TYPE
      mime-type: text/xml,application/xml,application/json
    response:
      # 配置响应GZIP压缩
      enabled: true

logging:
  level:
    com.eurekatest.service.IServiceBusinessOrder: debug
