server:
  port: 51100

spring:
  application:
    name: server-mgr-config

# 统一注册至Eureka集群
eureka:
  instance:
    hostname: ctp.server-mgr-config
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  server:
    default: eureka
    mgr-config-port: ${server.port}
    mgr-eureka-master-port: 52100
    mgr-eureka-slaveOne-port: 52101
    mgr-eureka-slaveTwo-port: 52102
    mgr-config: ${eureka.instance.hostname}
    mgr-eureka-master: ctp.server-mgr-eureka.master
    mgr-eureka-slaveOne: ctp.server-mgr-eureka.slaveOne
    mgr-eureka-slaveTwo: ctp.server-mgr-eureka.slaveTwo
  client:
    serviceUrl:
      defaultZone: http://${eureka.server.mgr-eureka-master}:${eureka.server.mgr-eureka-master-port}/${eureka.server.default}/,http://${eureka.server.mgr-eureka-slaveOne}:${eureka.server.mgr-eureka-slaveOne-port}/${eureka.server.default}/,http://${eureka.server.mgr-eureka-slaveTwo}:${eureka.server.mgr-eureka-slaveTwo-port}/${eureka.server.default}/
