spring:
  cloud:
    config:
      server:
        git:
          uri: http://172.16.20.71:8081/CavanLiu/server-mgr-config-test.git
          search-paths: /service-business-mall/,
            /service-business-order/,
            /service-mgr-zuul/
          username: yeying.liu@vonechain.com
          password: lyy841103
          default-label: master

